#!/usr/bin/env bash
# Displays listening ports. Includes listening sockets as well
# + as the PID and name of the program to which each socket belongs.
if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
