#!/usr/bin/env bash
#this is a comment
i=0
while ((i < 20))
do
	((i++))
	echo "$i"
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
done
